services:
  api:
    container_name: konnect-api
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      db:
        condition: service_healthy
    # volumes:
    #   - ./internal:/app/internal
    #   - ./cmd:/app/cmd
    develop:
      watch:
        - path: ./internal
          x-initial_sync: true
          action: rebuild
          target: /app/internal
        - path: ./cmd
          x-initial_sync: true
          action: rebuild
          target: /app/cmd
        - path: ./go.mod
          action: rebuild
        - path: ./go.sum
          action: rebuild
        - path: ./docker
          action: rebuild
        - path: ./docs
          x-initial_sync: true
          action: sync
          target: /app/docs
    networks:
      - konnect

  worker:
    container_name: konnect-worker
    build:
      context: .
      dockerfile: ./docker/worker.Dockerfile
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - konnect

  # extended postgres image with postgis
  db:
    image: postgis/postgis
    container_name: konnect-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USERNAME} -d ${DB_NAME}'"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - konnect

  redis:
    image: redis:8
    container_name: konnect-redis
    # take periodic snapshot every 60 seconds
    command: redis-server --requirepass ${REDIS_PASSWORD} --save 60 1 --loglevel warning
    ports:
      - ${REDIS_PORT}:6379
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - ./.redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  konnect:
volumes:
  .postgres-data:
  .redis-data:
